// PUAxControlTest1.idl : ActiveX コントロール プロジェクトのタイプ ライブラリ ソースです。

// このファイルは、PUAxControlTest1.ocx のリソース
// になるタイプ ライブラリ (PUAxControlTest1.tlb) を作成するために MIDL コンパイラ ツール
// PUAxControlTest1.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(9B863DD1-56F5-4CFA-A322-9B395C7AE831), version(1.0),
  control ]
library PUAxControlTest1Lib
{
	importlib(STDOLE_TLB);

	//  CPUAxControlTest1Ctrl のプライマリ ディスパッチ インターフェイスです。
	[ 
		uuid(B938336C-9D16-4E46-BC5A-39216FD2F97A)	
	]
	dispinterface _DPUAxControlTest1
	{
		properties:
		methods:
	};

	//  CPUAxControlTest1Ctrl のイベント ディスパッチ インターフェイスです。

	[ 
		uuid(75C0DE38-FBAD-42F4-950F-D4F893E77F75)	
	]
	dispinterface _DPUAxControlTest1Events
	{
		properties:
			//  イベント インターフェイスにプロパティがありません。

		methods:
	};

	//  CPUAxControlTest1Ctrl のクラス情報です。
	[
		uuid(83F0E680-C802-4532-8098-5FBA4C900C8F)
	]
	coclass PUAxControlTest1
	{
		[default] dispinterface _DPUAxControlTest1;
		[default, source] dispinterface _DPUAxControlTest1Events;
	};

};
